# Generated by Django 3.0.2 on 2020-01-20 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmplData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=3)),
                ('Attrition', models.CharField(max_length=6)),
                ('BusinessTravel', models.CharField(max_length=20)),
                ('DailyRate', models.CharField(max_length=6)),
                ('Department', models.CharField(max_length=30)),
                ('DistanceFromHome', models.CharField(max_length=6)),
                ('Education', models.CharField(max_length=6)),
                ('EducationField', models.CharField(max_length=30)),
                ('EmployeeCount', models.CharField(max_length=10)),
                ('EmployeeNumber', models.CharField(max_length=10)),
                ('EnvironmentSatisfaction', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('HourlyRate', models.CharField(max_length=6)),
                ('JobInvolvement', models.CharField(max_length=6)),
                ('JobLevel', models.CharField(max_length=6)),
                ('JobRole', models.CharField(max_length=20)),
                ('JobSatisfaction', models.CharField(max_length=6)),
                ('MaritalStatus', models.CharField(max_length=20)),
                ('MonthlyIncome', models.CharField(max_length=20)),
                ('MonthlyRate', models.CharField(max_length=20)),
                ('NumCompaniesWorked', models.CharField(max_length=10)),
                ('Over18', models.CharField(max_length=6)),
                ('OverTime', models.CharField(max_length=6)),
                ('PercentSalaryHike', models.CharField(max_length=10)),
                ('PerformanceRating', models.CharField(max_length=10)),
                ('RelationshipSatisfaction', models.CharField(max_length=10)),
                ('StandardHours', models.CharField(max_length=10)),
                ('StockOptionLevel', models.CharField(max_length=10)),
                ('TotalWorkingYears', models.CharField(max_length=10)),
                ('TrainingTimesLastYear', models.CharField(max_length=10)),
                ('WorkLifeBalance', models.CharField(max_length=10)),
                ('YearsAtCompany', models.CharField(max_length=10)),
                ('YearsInCurrentRole', models.CharField(max_length=10)),
                ('YearsSinceLastPromotion', models.CharField(max_length=10)),
                ('YearsWithCurrManager', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaffTurnoverApp.UserInfo')),
            ],
        ),
    ]
