# Generated by Django 3.0.2 on 2020-01-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffTurnoverApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empldata',
            name='BusinessTravel',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='empldata',
            name='Department',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='empldata',
            name='EducationField',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='empldata',
            name='JobRole',
            field=models.CharField(max_length=40),
        ),
    ]
